services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend/LostifyIfFindify
    ports:
      - "3000:80"
    depends_on:
      - backend